### ISSUE TITLE
vue-datepicker.vue Unexpected token <

### ISSUE THREAD

**Issue by smarbos** [hilongjw/vue-datepicker#91]
Hello, im using NuxtJS with Vue2, 

I've followed the instructions and im getting a Vue.js error

```
/home/smarbos/camba/devel/nuxt-dos/node_modules/vue-datepicker/vue-datepicker.vue:1
(function (exports, require, module, __filename, __dirname) { <style scoped>
                                                              ^
SyntaxError: Unexpected token <
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (__vue_ssr_bundle__:4366:18)
    at __webpack_require__ (__vue_ssr_bundle__:21:30)
```
I'm doing something wrong?

Node  v7.5.0
Npm v4.1.2

Thanks!

**Comment by wushan** [comment]
I am facing the same problem here, but it works well when I was developing the project 2 month ago.

I ran into this problem today when trying to ```npm run dev``` nuxt.

**Comment by lx4r** [comment]
Same problem, I'm working with Electron and Vue 2. For me it occurred right after installing the datepicker via NPM.

A part of my vue component:

```js
<script>
  import myDatepicker from 'vue-datepicker'

  export default {
    components: {
      'date-picker': myDatepicker
    }
```

Node 6.10.0

**Comment by Darkside73** [comment]
Same problem with nuxt

**Comment by Jeffreyrn** [comment]
+1

**Comment by Jutanium** [comment]
Same problem with nuxt

**Comment by SteveJay7** [comment]
same problem here

**Comment by danieloprado** [comment]
workaround:
import Datepicker from 'vue-datepicker/vue-datepicker-es6.vue';
